[project]
src = "src"
out = "out"
dot_env = ".env"
save_abi_path = "abis"
default_network_name = "base-mainnet-fork"

[networks.contracts]
# Core
weth = { abi = "abis/weth.json" }

# Virtual
ffactory = {abi = "abis/FFactory.json"}
virtual_token = {abi = "abis/VirtualToken.json"}
bonding = {abi = "abis/Bonding.json"}
agent_factory = {abi = "abis/AgentFactoryV3.json"}
agent_token = {abi = "abis/AgentToken.json"}
ferc20 = {abi = "abis/FERC20.json"}
fpair = {abi = "abis/FPair.json"}

# Uniswap
uniswap_swap_router = { abi = "abis/uniswap_swap_router.json" }

[networks.base-mainnet-fork]
fork = true
url = "$BASE_MAINNET_RPC_URL"
default_account_name = "anvil0"
unsafe_password_file = "$UNSAFE_PS_FILE"

[networks.base-mainnet-fork.contracts]
# Core
weth = { address = "0x4200000000000000000000000000000000000006" }

# Virtual
ffactory = { address = "0x158d7CcaA23DC3c8861c3323eD546E3d25e74309" }
virtual_token = { address = "0x0b3e328455c4059EEb9e3f84b5543F74E24e7E1b" }
bonding = { address = "0xF66DeA7b3e897cD44A5a231c61B6B4423d613259"}
agent_factory = { address = "0x71B8EFC8BCaD65a5D9386D07f2Dff57ab4EAf533" }
agent_token = { address = "0x731814e491571A2e9eE3c5b1F7f3b962eE8f4870" }
ferc20 = { address = "0x2072Ebe65d2Def584551D6b14c629BD0D68FE396" }

# Uniswap
uniswap_swap_router = { address = "0x2626664c2603336E57B271c5C0b26F421741e481" }

#agent_token_contract = { address = "0x8f15c3f0e30094C6E92190Ae442DD7BAB840024f" } might not be needed
# Add the virtual factory
# Add the virtual AgentToken
# Add the virtual AgentTokenFactory
# Add the virtual Router
# Add weth
# Add ??? 16536

# You can view all configuration options at https://cyfrin.github.io/moccasin/all_moccasin_toml_parameters.html

