[project]
src = "src"
out = "out"
dot_env = ".env"
save_abi_path = "abis"
default_network_name = "base-mainnet-fork"

[networks.contracts]
# Add the virtual factory
# Add the virtual AgentToken
# Add the virtual AgentTokenFactory
# Add the virtual Router
# Add weth
# Add ???

[networks.base-mainnet-fork]
fork = true
url = "$BASE_MAINNET_RPC_URL"
default_account_name = "anvil0"
unsafe_password_file = "$UNSAFE_PASSWORD_FILE"

[networks.base-mainnet-fork.contracts]
# Add the virtual factory
# Add the virtual AgentToken
# Add the virtual AgentTokenFactory
# Add the virtual Router
# Add weth
# Add ???

# You can view all configuration options at https://cyfrin.github.io/moccasin/all_moccasin_toml_parameters.html

